name: Python package
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - "3.10"
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          submodules: recursive
      - name: Install dependencies
        with:
          submodules: recursive
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pytest
          pip install -r tpjt-tistoryuploader-src/requirements.txt
      - name: Auto Scheduler
        with:
          submodules: recursive
        env:
          GH_ID: ${{ secrets.GH_ID }}
          GH_REPO: ${{ secrets.GH_REPO }}
          TSESSION: ${{ secrets.TSESSION }}
          TISTORY_BLOG_DOMAIN: ${{ secrets.TISTORY_BLOG_DOMAIN }}
        run: |
          # stop the build if there are Python syntax errors or undefined names
          python tpjt-tistoryuploader-src/application.py
